const grid=document.querySelector('#cardGrid'),template=document.querySelector('#cardTemplate'),composer=document.querySelector('#composer'),form=document.querySelector('#composerForm'),filters=[...document.querySelectorAll('.filter')];
let cards=[],comments=[],currentFilter='all',editingId=null,composerType='regular';
const ownerToken=localStorage.getItem('sm-owner-token')||crypto.randomUUID();localStorage.setItem('sm-owner-token',ownerToken);
const owned=new Set(JSON.parse(localStorage.getItem('sm-owned')||'[]'));
const oldLocal=JSON.parse(localStorage.getItem('speckled-mushroom-cards')||'[]');
const saveOwned=()=>localStorage.setItem('sm-owned',JSON.stringify([...owned]));
async function api(method,body,url='/api'){const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});if(!r.ok){const e=await r.json().catch(()=>({}));throw new Error(e.error||'Request failed')}return r.json()}
async function load(){try{let d=await api('GET');cards=d.wiggles;comments=d.comments||[];if(oldLocal.length){for(const w of oldLocal){try{await api('POST',{action:'wiggle',...w,author:'guest',ownerToken});owned.add(w.id)}catch{}}saveOwned();localStorage.removeItem('speckled-mushroom-cards');d=await api('GET');cards=d.wiggles;comments=d.comments||[]}}catch(e){console.error(e);cards=oldLocal}render()}
function openImage(src,title){let d=document.querySelector('#imageViewer');if(!d){d=document.createElement('dialog');d.id='imageViewer';d.className='image-viewer';d.innerHTML='<button class="image-viewer-close" aria-label="Close">×</button><img alt="">';document.body.appendChild(d);d.querySelector('button').onclick=()=>d.close();d.onclick=e=>{if(e.target===d)d.close()}}const i=d.querySelector('img');i.src=src;i.alt=title||'Wiggle image';d.showModal()}
function slugify(s){return String(s||'wiggle').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'wiggle'}
function render(){grid.innerHTML='';cards.filter(c=>currentFilter==='all'||c.kind===currentFilter).forEach(card=>{const node=template.content.cloneNode(true),article=node.querySelector('.card'),wrap=node.querySelector('.card-image-wrap'),img=node.querySelector('.card-image');node.querySelector('.card-title').textContent=card.title;node.querySelector('.card-text').textContent=card.text||'';node.querySelector('.kind').textContent=card.kind==='link'?'Link':card.kind==='image'?'Picture':'Words';const visit=node.querySelector('.visit-link');if(card.url){visit.href=card.url;if(card.kind==='link'){article.classList.add('link-wiggle');article.title='Open '+card.url;article.onclick=e=>{if(e.target.closest('button,input,textarea,form,a,.comments'))return;window.open(card.url,'_blank','noopener,noreferrer')}}}else visit.remove();node.querySelector('.handle').textContent='@'+(card.author||'guest');if(card.image){article.classList.add('has-image');img.src=card.image;img.alt=card.title;if(card.kind!=='link'){wrap.classList.add('zoomable');wrap.title='Open larger image';wrap.onclick=e=>{e.stopPropagation();openImage(card.image,card.title)}}}else wrap.remove();const edit=node.querySelector('.edit-btn'),del=node.querySelector('.delete-btn'),share=node.querySelector('.actual-share');if(!owned.has(card.id)){edit.remove();del.remove()}else{edit.onclick=()=>openEdit(card);del.onclick=async()=>{if(confirm('Delete this Wiggle? This cannot be undone.')){await api('DELETE',null,'/api?id='+encodeURIComponent(card.id)+'&token='+encodeURIComponent(ownerToken));await load()}}}share.onclick=async()=>{const data={title:card.title,text:card.text||card.title,url:location.origin+'/wiggle/'+slugify(card.title)+'-'+encodeURIComponent(card.id)};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(data.url);share.textContent='Copied';setTimeout(()=>share.textContent='Share',1200)}}catch{}};const list=node.querySelector('.comment-list'),count=node.querySelector('.comment-count'),cf=node.querySelector('.comment-form'),mine=comments.filter(c=>c.wiggle_id===card.id);count.textContent=mine.length?mine.length+' comment'+(mine.length===1?'':'s'):'Comments';mine.forEach(c=>{const d=document.createElement('div');d.className='comment';const s=document.createElement('strong');s.textContent=c.author||'guest';const p=document.createElement('p');p.textContent=c.body;d.append(s,p);list.appendChild(d)});cf.onsubmit=async e=>{e.preventDefault();const name=cf.querySelector('[name=name]').value.trim()||'guest',body=cf.querySelector('[name=comment]').value.trim();if(!body)return;await api('POST',{action:'comment',wiggleId:card.id,author:name,body});cf.reset();await load()};article.id=card.id;grid.appendChild(node)})}
function setType(t){composerType=t;document.querySelectorAll('.type-btn').forEach(b=>b.classList.toggle('active',b.dataset.type===t));linkMaker.hidden=t!=='link'}document.querySelectorAll('.type-btn').forEach(b=>b.onclick=()=>setType(b.dataset.type));makePreview.onclick=async()=>{const url=sourceUrl.value.trim();if(!url)return;previewStatus.textContent='Growing your preview…';try{const d=await api('POST',{url},'/api/preview');cardTitle.value=d.title||'';cardText.value=d.description||'';cardImage.value=d.image||'';sourceUrl.value=d.url;previewStatus.textContent='Preview ready — change anything you like, then post it.'}catch(e){previewStatus.textContent=e.message}};
function openNew(){editingId=null;form.reset();setType('regular');composerEyebrow.textContent='NEW WIGGLE';composerHeading.textContent='Add a Wiggle';postCard.textContent='Post Wiggle';composer.showModal()}
function openEdit(c){editingId=c.id;setType(c.kind==='link'?'link':'regular');sourceUrl.value=c.url||'';cardTitle.value=c.title;cardText.value=c.text||'';cardImage.value=c.image||'';composerEyebrow.textContent='EDIT WIGGLE';composerHeading.textContent='Fix your Wiggle';postCard.textContent='Save changes';composer.showModal()}
openComposer.onclick=openNew;heroAdd.onclick=openNew;filters.forEach(b=>b.onclick=()=>{filters.forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;render()});
form.onsubmit=async e=>{if(!e.submitter||e.submitter.value==='cancel')return;e.preventDefault();const payload={id:editingId,title:cardTitle.value.trim(),text:cardText.value.trim(),image:cardImage.value.trim(),url:composerType==='link'?sourceUrl.value.trim():'',kind:composerType==='link'?'link':undefined,ownerToken,author:'guest'};if(!payload.title)return;try{if(editingId)await api('PUT',payload);else{delete payload.id;const r=await api('POST',{action:'wiggle',...payload});owned.add(r.id);saveOwned()}composer.close();await load()}catch(err){alert(err.message)}};
composer.addEventListener('close',()=>{editingId=null;form.reset()});load().then?.(()=>{});