const { neon } = require('@neondatabase/serverless');
const crypto = require('crypto');
const sql = neon(process.env.POSTGRES_URL);
const clean = (v,n) => String(v||'').trim().slice(0,n);
async function init(){
 await sql.query("CREATE TABLE IF NOT EXISTS wiggles (id TEXT PRIMARY KEY,title VARCHAR(80) NOT NULL,body VARCHAR(500) DEFAULT '',image TEXT DEFAULT '',kind VARCHAR(10) NOT NULL DEFAULT 'text',author VARCHAR(40) NOT NULL DEFAULT 'guest',owner_token TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())");
 await sql.query("CREATE TABLE IF NOT EXISTS comments (id BIGSERIAL PRIMARY KEY,wiggle_id TEXT NOT NULL REFERENCES wiggles(id) ON DELETE CASCADE,author VARCHAR(40) NOT NULL DEFAULT 'guest',body VARCHAR(500) NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())");
}
module.exports=async(req,res)=>{try{await init();
if(req.method==='GET'){const wiggles=await sql.query('SELECT id,title,body AS text,image,kind,author,created_at FROM wiggles ORDER BY created_at DESC LIMIT 200');const comments=await sql.query('SELECT id,wiggle_id,author,body,created_at FROM comments ORDER BY created_at ASC');return res.status(200).json({wiggles,comments});}
if(req.method==='POST'){const b=req.body||{};if(b.action==='wiggle'){const id=clean(b.id,100)||('wiggle-'+Date.now()+'-'+crypto.randomBytes(3).toString('hex'));const title=clean(b.title,80),body=clean(b.text,500),image=clean(b.image,2000),author=clean(b.author,40)||'guest',token=clean(b.ownerToken,120);if(!title||!token)return res.status(400).json({error:'Title and owner token required'});const kind=image?'image':'text';await sql.query('INSERT INTO wiggles (id,title,body,image,kind,author,owner_token) VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT (id) DO NOTHING',[id,title,body,image,kind,author,token]);return res.status(201).json({ok:true,id});}if(b.action==='comment'){const wid=clean(b.wiggleId,100),author=clean(b.author,40)||'guest',body=clean(b.body,500);if(!wid||!body)return res.status(400).json({error:'Comment required'});await sql.query('INSERT INTO comments (wiggle_id,author,body) VALUES ($1,$2,$3)',[wid,author,body]);return res.status(201).json({ok:true});}return res.status(400).json({error:'Unknown action'});}
if(req.method==='PUT'){const b=req.body||{},id=clean(b.id,100),token=clean(b.ownerToken,120),title=clean(b.title,80),body=clean(b.text,500),image=clean(b.image,2000),kind=image?'image':'text';if(!id||!token||!title)return res.status(400).json({error:'Missing fields'});const r=await sql.query('UPDATE wiggles SET title=$1,body=$2,image=$3,kind=$4 WHERE id=$5 AND owner_token=$6 RETURNING id',[title,body,image,kind,id,token]);return r.length?res.status(200).json({ok:true}):res.status(403).json({error:'Not allowed'});}
if(req.method==='DELETE'){const id=clean(req.query.id,100),token=clean(req.query.token,120);const r=await sql.query('DELETE FROM wiggles WHERE id=$1 AND owner_token=$2 RETURNING id',[id,token]);return r.length?res.status(200).json({ok:true}):res.status(403).json({error:'Not allowed'});}
res.setHeader('Allow','GET, POST, PUT, DELETE');return res.status(405).end();
}catch(e){console.error(e);return res.status(500).json({error:'Speckled Mushroom had a wobble.'});}};